### ISSUE TITLE
cannot build "npm install"

### ISSUE THREAD

**Issue by mbandu** [fechy/alexa-upnp-device-emulator#1]
i am having the following error when building npm install

> core-js@2.6.10 postinstall E:\alexa-upnp-device-emulator\node_modules\webpack-cli\node_modules\webpack-addons\node_modules\jscodeshift\node_modules\babel-preset-stage-1\node_modules\babel-preset-stage-2\node_modules\babel-preset-stage-3\node_modules\babel-plugin-transform-exponentiation-operator\node_modules\babel-runtime\node_modules\core-js
> node postinstall || echo "ignore"

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! core-js@2.6.10 postinstall: `node postinstall || echo "ignore"`
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the core-js@2.6.10 postinstall script 'node postinstall || echo "ignore"'.
npm ERR! This is most likely a problem with the core-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall || echo "ignore"
npm ERR! You can get their info via:
npm ERR!     npm owner ls core-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\alexa-upnp-device-emulator\npm-debug.log

can you help?

**Comment by fechy** [comment]
I just updated the dependencies and seems to be working again. Make sure you pull my latest changes and try again.
Maybe delete node_modules before ;)
